apiVersion: v1
kind: Service
metadata:
  name: {{ include "voting-app-helm.fullname" . }}
  labels:
    {{- include "voting-app-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    {{- include "voting-app-helm.selectorLabels" . | nindent 4 }}
    app: vote
