apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem #defaults to this if you don't specify volumeMode
  resources:
    requests:
      storage: 1Gi
  # storageClassName: ebs-sc #optional, but recommended for AWS EBS volumes.